/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BudgetRange {
  'max' : bigint,
  'min' : bigint,
  'currency' : string,
}
export interface ConsultationRequest {
  'id' : string,
  'status' : string,
  'userId' : Principal,
  'projectId' : [] | [string],
  'notes' : string,
  'submissionDate' : Time,
  'requestedTime' : Time,
}
export interface Designer {
  'id' : string,
  'bio' : string,
  'portfolio' : Array<PortfolioItem>,
  'styles' : Array<StylePreference>,
  'name' : string,
}
export interface Package {
  'id' : string,
  'features' : Array<string>,
  'name' : string,
  'description' : string,
  'priceINR' : bigint,
}
export interface PortfolioItem {
  'id' : string,
  'description' : string,
  'style' : StylePreference,
  'imageUrl' : string,
}
export interface Product {
  'id' : string,
  'stylePreference' : StylePreference,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'priceINR' : bigint,
  'roomType' : RoomType,
}
export interface ProductCategory {
  'id' : string,
  'name' : string,
  'description' : string,
  'products' : Array<Product>,
}
export interface ProjectBrief {
  'id' : string,
  'status' : string,
  'userId' : Principal,
  'submissionDate' : Time,
  'selectedPackage' : [] | [string],
  'stylePreferences' : Array<StylePreference>,
  'budget' : BudgetRange,
  'roomType' : RoomType,
  'timeline' : string,
}
export interface ProjectNote {
  'id' : string,
  'userId' : Principal,
  'projectId' : string,
  'message' : string,
  'timestamp' : Time,
}
export type RoomType = { 'bedroom' : null } |
  { 'other' : string } |
  { 'kidsRoom' : null } |
  { 'office' : null } |
  { 'livingRoom' : null } |
  { 'diningRoom' : null };
export type StylePreference = { 'other' : string } |
  { 'rustic' : null } |
  { 'boho' : null } |
  { 'traditional' : null } |
  { 'minimalist' : null } |
  { 'modern' : null } |
  { 'contemporary' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'address' : [] | [string],
  'stylePreferences' : Array<StylePreference>,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDesigner' : ActorMethod<[Designer], undefined>,
  'addNote' : ActorMethod<[ProjectNote], undefined>,
  'addPackage' : ActorMethod<[Package], undefined>,
  'addProductCategory' : ActorMethod<[ProductCategory], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProjectBrief' : ActorMethod<[ProjectBrief], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConsultationsForProject' : ActorMethod<
    [string],
    Array<ConsultationRequest>
  >,
  'getDesigners' : ActorMethod<[], Array<Designer>>,
  'getNotesForProject' : ActorMethod<[string], Array<ProjectNote>>,
  'getPackages' : ActorMethod<[], Array<Package>>,
  'getProductCategories' : ActorMethod<[], Array<ProductCategory>>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getProjectBrief' : ActorMethod<[string], [] | [ProjectBrief]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProjectBriefs' : ActorMethod<[Principal], Array<ProjectBrief>>,
  'initializeProductCategories' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'requestConsultation' : ActorMethod<[ConsultationRequest], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];