/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const StylePreference = IDL.Variant({
  'other' : IDL.Text,
  'rustic' : IDL.Null,
  'boho' : IDL.Null,
  'traditional' : IDL.Null,
  'minimalist' : IDL.Null,
  'modern' : IDL.Null,
  'contemporary' : IDL.Null,
});
export const PortfolioItem = IDL.Record({
  'id' : IDL.Text,
  'description' : IDL.Text,
  'style' : StylePreference,
  'imageUrl' : IDL.Text,
});
export const Designer = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Text,
  'portfolio' : IDL.Vec(PortfolioItem),
  'styles' : IDL.Vec(StylePreference),
  'name' : IDL.Text,
});
export const Time = IDL.Int;
export const ProjectNote = IDL.Record({
  'id' : IDL.Text,
  'userId' : IDL.Principal,
  'projectId' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const Package = IDL.Record({
  'id' : IDL.Text,
  'features' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'priceINR' : IDL.Nat,
});
export const RoomType = IDL.Variant({
  'bedroom' : IDL.Null,
  'other' : IDL.Text,
  'kidsRoom' : IDL.Null,
  'office' : IDL.Null,
  'livingRoom' : IDL.Null,
  'diningRoom' : IDL.Null,
});
export const RoomPackage = IDL.Record({
  'id' : IDL.Text,
  'productIds' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'style' : StylePreference,
  'priceINR' : IDL.Nat,
  'roomType' : RoomType,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BudgetRange = IDL.Record({
  'max' : IDL.Nat,
  'min' : IDL.Nat,
  'currency' : IDL.Text,
});
export const ProjectBrief = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'userId' : IDL.Principal,
  'submissionDate' : Time,
  'selectedPackage' : IDL.Opt(IDL.Text),
  'stylePreferences' : IDL.Vec(StylePreference),
  'budget' : BudgetRange,
  'roomType' : RoomType,
  'timeline' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'address' : IDL.Opt(IDL.Text),
  'stylePreferences' : IDL.Vec(StylePreference),
  'phone' : IDL.Text,
});
export const ConsultationRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'userId' : IDL.Principal,
  'projectId' : IDL.Opt(IDL.Text),
  'notes' : IDL.Text,
  'submissionDate' : Time,
  'requestedTime' : Time,
});
export const FurnitureSubCategory = IDL.Variant({
  'bedSideTables' : IDL.Null,
  'sofa' : IDL.Null,
  'sofaChairs' : IDL.Null,
  'cornerTable' : IDL.Null,
  'studyTable' : IDL.Null,
  'kingSizeBed' : IDL.Null,
  'recliners' : IDL.Null,
  'crockeryUnit' : IDL.Null,
  'queenSizeBed' : IDL.Null,
  'dressingTable' : IDL.Null,
  'centerTable' : IDL.Null,
  'diningTable' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'stylePreference' : StylePreference,
  'inventory' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'brandId' : IDL.Text,
  'priceINR' : IDL.Nat,
  'roomType' : RoomType,
});
export const FurnitureCategory = IDL.Record({
  'id' : IDL.Text,
  'subCategory' : FurnitureSubCategory,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'products' : IDL.Vec(Product),
});
export const DeliveryAddress = IDL.Record({
  'country' : IDL.Text,
  'city' : IDL.Text,
  'postalCode' : IDL.Text,
  'fullName' : IDL.Text,
  'state' : IDL.Text,
  'addressLine1' : IDL.Text,
  'addressLine2' : IDL.Opt(IDL.Text),
  'phoneNumber' : IDL.Text,
});
export const PaymentMethod = IDL.Variant({
  'upi' : IDL.Null,
  'wallet' : IDL.Null,
  'netBanking' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'productId' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'deliveryAddress' : DeliveryAddress,
  'paymentMethod' : PaymentMethod,
  'createdAt' : Time,
  'totalAmount' : IDL.Nat,
  'buyerId' : IDL.Principal,
  'items' : IDL.Vec(OrderItem),
});
export const ProductBrand = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'logoUrl' : IDL.Text,
});
export const ProductCategory = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'products' : IDL.Vec(Product),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDesigner' : IDL.Func([Designer], [], []),
  'addNote' : IDL.Func([ProjectNote], [], []),
  'addPackage' : IDL.Func([Package], [], []),
  'addRoomPackage' : IDL.Func([RoomPackage], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProjectBrief' : IDL.Func([ProjectBrief], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConsultationsForProject' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ConsultationRequest)],
      ['query'],
    ),
  'getDesigners' : IDL.Func([], [IDL.Vec(Designer)], ['query']),
  'getFurnitureCategories' : IDL.Func(
      [],
      [IDL.Vec(FurnitureCategory)],
      ['query'],
    ),
  'getNotesForProject' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ProjectNote)],
      ['query'],
    ),
  'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
  'getPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
  'getProductBrands' : IDL.Func([], [IDL.Vec(ProductBrand)], ['query']),
  'getProductCategories' : IDL.Func([], [IDL.Vec(ProductCategory)], ['query']),
  'getProductsByBrand' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getProductsByFurnitureCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getProductsByFurnitureSubCategory' : IDL.Func(
      [FurnitureSubCategory],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getProductsForRoomPackage' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getProjectBrief' : IDL.Func([IDL.Text], [IDL.Opt(ProjectBrief)], ['query']),
  'getRoomPackageById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(RoomPackage)],
      ['query'],
    ),
  'getRoomPackages' : IDL.Func([], [IDL.Vec(RoomPackage)], ['query']),
  'getRoomPackagesByRoomType' : IDL.Func(
      [RoomType],
      [IDL.Vec(RoomPackage)],
      ['query'],
    ),
  'getRoomPackagesByStyle' : IDL.Func(
      [StylePreference],
      [IDL.Vec(RoomPackage)],
      ['query'],
    ),
  'getRoomPackagesByStyleAndRoomType' : IDL.Func(
      [StylePreference, RoomType],
      [IDL.Vec(RoomPackage)],
      ['query'],
    ),
  'getStyleOptionsForRoomType' : IDL.Func(
      [RoomType],
      [IDL.Vec(StylePreference)],
      ['query'],
    ),
  'getUserOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProjectBriefs' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ProjectBrief)],
      ['query'],
    ),
  'globalProductSearch' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([Order], [], []),
  'requestConsultation' : IDL.Func([ConsultationRequest], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchFurnitureProducts' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Product)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const StylePreference = IDL.Variant({
    'other' : IDL.Text,
    'rustic' : IDL.Null,
    'boho' : IDL.Null,
    'traditional' : IDL.Null,
    'minimalist' : IDL.Null,
    'modern' : IDL.Null,
    'contemporary' : IDL.Null,
  });
  const PortfolioItem = IDL.Record({
    'id' : IDL.Text,
    'description' : IDL.Text,
    'style' : StylePreference,
    'imageUrl' : IDL.Text,
  });
  const Designer = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Text,
    'portfolio' : IDL.Vec(PortfolioItem),
    'styles' : IDL.Vec(StylePreference),
    'name' : IDL.Text,
  });
  const Time = IDL.Int;
  const ProjectNote = IDL.Record({
    'id' : IDL.Text,
    'userId' : IDL.Principal,
    'projectId' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const Package = IDL.Record({
    'id' : IDL.Text,
    'features' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'priceINR' : IDL.Nat,
  });
  const RoomType = IDL.Variant({
    'bedroom' : IDL.Null,
    'other' : IDL.Text,
    'kidsRoom' : IDL.Null,
    'office' : IDL.Null,
    'livingRoom' : IDL.Null,
    'diningRoom' : IDL.Null,
  });
  const RoomPackage = IDL.Record({
    'id' : IDL.Text,
    'productIds' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'style' : StylePreference,
    'priceINR' : IDL.Nat,
    'roomType' : RoomType,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BudgetRange = IDL.Record({
    'max' : IDL.Nat,
    'min' : IDL.Nat,
    'currency' : IDL.Text,
  });
  const ProjectBrief = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'userId' : IDL.Principal,
    'submissionDate' : Time,
    'selectedPackage' : IDL.Opt(IDL.Text),
    'stylePreferences' : IDL.Vec(StylePreference),
    'budget' : BudgetRange,
    'roomType' : RoomType,
    'timeline' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'address' : IDL.Opt(IDL.Text),
    'stylePreferences' : IDL.Vec(StylePreference),
    'phone' : IDL.Text,
  });
  const ConsultationRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'userId' : IDL.Principal,
    'projectId' : IDL.Opt(IDL.Text),
    'notes' : IDL.Text,
    'submissionDate' : Time,
    'requestedTime' : Time,
  });
  const FurnitureSubCategory = IDL.Variant({
    'bedSideTables' : IDL.Null,
    'sofa' : IDL.Null,
    'sofaChairs' : IDL.Null,
    'cornerTable' : IDL.Null,
    'studyTable' : IDL.Null,
    'kingSizeBed' : IDL.Null,
    'recliners' : IDL.Null,
    'crockeryUnit' : IDL.Null,
    'queenSizeBed' : IDL.Null,
    'dressingTable' : IDL.Null,
    'centerTable' : IDL.Null,
    'diningTable' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'stylePreference' : StylePreference,
    'inventory' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'brandId' : IDL.Text,
    'priceINR' : IDL.Nat,
    'roomType' : RoomType,
  });
  const FurnitureCategory = IDL.Record({
    'id' : IDL.Text,
    'subCategory' : FurnitureSubCategory,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'products' : IDL.Vec(Product),
  });
  const DeliveryAddress = IDL.Record({
    'country' : IDL.Text,
    'city' : IDL.Text,
    'postalCode' : IDL.Text,
    'fullName' : IDL.Text,
    'state' : IDL.Text,
    'addressLine1' : IDL.Text,
    'addressLine2' : IDL.Opt(IDL.Text),
    'phoneNumber' : IDL.Text,
  });
  const PaymentMethod = IDL.Variant({
    'upi' : IDL.Null,
    'wallet' : IDL.Null,
    'netBanking' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'productId' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'deliveryAddress' : DeliveryAddress,
    'paymentMethod' : PaymentMethod,
    'createdAt' : Time,
    'totalAmount' : IDL.Nat,
    'buyerId' : IDL.Principal,
    'items' : IDL.Vec(OrderItem),
  });
  const ProductBrand = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'logoUrl' : IDL.Text,
  });
  const ProductCategory = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'products' : IDL.Vec(Product),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDesigner' : IDL.Func([Designer], [], []),
    'addNote' : IDL.Func([ProjectNote], [], []),
    'addPackage' : IDL.Func([Package], [], []),
    'addRoomPackage' : IDL.Func([RoomPackage], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProjectBrief' : IDL.Func([ProjectBrief], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConsultationsForProject' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ConsultationRequest)],
        ['query'],
      ),
    'getDesigners' : IDL.Func([], [IDL.Vec(Designer)], ['query']),
    'getFurnitureCategories' : IDL.Func(
        [],
        [IDL.Vec(FurnitureCategory)],
        ['query'],
      ),
    'getNotesForProject' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProjectNote)],
        ['query'],
      ),
    'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
    'getPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
    'getProductBrands' : IDL.Func([], [IDL.Vec(ProductBrand)], ['query']),
    'getProductCategories' : IDL.Func(
        [],
        [IDL.Vec(ProductCategory)],
        ['query'],
      ),
    'getProductsByBrand' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsByFurnitureCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsByFurnitureSubCategory' : IDL.Func(
        [FurnitureSubCategory],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsForRoomPackage' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProjectBrief' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ProjectBrief)],
        ['query'],
      ),
    'getRoomPackageById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(RoomPackage)],
        ['query'],
      ),
    'getRoomPackages' : IDL.Func([], [IDL.Vec(RoomPackage)], ['query']),
    'getRoomPackagesByRoomType' : IDL.Func(
        [RoomType],
        [IDL.Vec(RoomPackage)],
        ['query'],
      ),
    'getRoomPackagesByStyle' : IDL.Func(
        [StylePreference],
        [IDL.Vec(RoomPackage)],
        ['query'],
      ),
    'getRoomPackagesByStyleAndRoomType' : IDL.Func(
        [StylePreference, RoomType],
        [IDL.Vec(RoomPackage)],
        ['query'],
      ),
    'getStyleOptionsForRoomType' : IDL.Func(
        [RoomType],
        [IDL.Vec(StylePreference)],
        ['query'],
      ),
    'getUserOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProjectBriefs' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ProjectBrief)],
        ['query'],
      ),
    'globalProductSearch' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([Order], [], []),
    'requestConsultation' : IDL.Func([ConsultationRequest], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchFurnitureProducts' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };