/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const StylePreference = IDL.Variant({
  'other' : IDL.Text,
  'rustic' : IDL.Null,
  'boho' : IDL.Null,
  'traditional' : IDL.Null,
  'minimalist' : IDL.Null,
  'modern' : IDL.Null,
  'contemporary' : IDL.Null,
});
export const PortfolioItem = IDL.Record({
  'id' : IDL.Text,
  'description' : IDL.Text,
  'style' : StylePreference,
  'imageUrl' : IDL.Text,
});
export const Designer = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Text,
  'portfolio' : IDL.Vec(PortfolioItem),
  'styles' : IDL.Vec(StylePreference),
  'name' : IDL.Text,
});
export const Time = IDL.Int;
export const ProjectNote = IDL.Record({
  'id' : IDL.Text,
  'userId' : IDL.Principal,
  'projectId' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const Package = IDL.Record({
  'id' : IDL.Text,
  'features' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'priceINR' : IDL.Nat,
});
export const RoomType = IDL.Variant({
  'bedroom' : IDL.Null,
  'other' : IDL.Text,
  'kidsRoom' : IDL.Null,
  'office' : IDL.Null,
  'livingRoom' : IDL.Null,
  'diningRoom' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'stylePreference' : StylePreference,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'priceINR' : IDL.Nat,
  'roomType' : RoomType,
});
export const ProductCategory = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'products' : IDL.Vec(Product),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BudgetRange = IDL.Record({
  'max' : IDL.Nat,
  'min' : IDL.Nat,
  'currency' : IDL.Text,
});
export const ProjectBrief = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'userId' : IDL.Principal,
  'submissionDate' : Time,
  'selectedPackage' : IDL.Opt(IDL.Text),
  'stylePreferences' : IDL.Vec(StylePreference),
  'budget' : BudgetRange,
  'roomType' : RoomType,
  'timeline' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'address' : IDL.Opt(IDL.Text),
  'stylePreferences' : IDL.Vec(StylePreference),
  'phone' : IDL.Text,
});
export const ConsultationRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'userId' : IDL.Principal,
  'projectId' : IDL.Opt(IDL.Text),
  'notes' : IDL.Text,
  'submissionDate' : Time,
  'requestedTime' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDesigner' : IDL.Func([Designer], [], []),
  'addNote' : IDL.Func([ProjectNote], [], []),
  'addPackage' : IDL.Func([Package], [], []),
  'addProductCategory' : IDL.Func([ProductCategory], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProjectBrief' : IDL.Func([ProjectBrief], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConsultationsForProject' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ConsultationRequest)],
      ['query'],
    ),
  'getDesigners' : IDL.Func([], [IDL.Vec(Designer)], ['query']),
  'getNotesForProject' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ProjectNote)],
      ['query'],
    ),
  'getPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
  'getProductCategories' : IDL.Func([], [IDL.Vec(ProductCategory)], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getProjectBrief' : IDL.Func([IDL.Text], [IDL.Opt(ProjectBrief)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProjectBriefs' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ProjectBrief)],
      ['query'],
    ),
  'initializeProductCategories' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'requestConsultation' : IDL.Func([ConsultationRequest], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const StylePreference = IDL.Variant({
    'other' : IDL.Text,
    'rustic' : IDL.Null,
    'boho' : IDL.Null,
    'traditional' : IDL.Null,
    'minimalist' : IDL.Null,
    'modern' : IDL.Null,
    'contemporary' : IDL.Null,
  });
  const PortfolioItem = IDL.Record({
    'id' : IDL.Text,
    'description' : IDL.Text,
    'style' : StylePreference,
    'imageUrl' : IDL.Text,
  });
  const Designer = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Text,
    'portfolio' : IDL.Vec(PortfolioItem),
    'styles' : IDL.Vec(StylePreference),
    'name' : IDL.Text,
  });
  const Time = IDL.Int;
  const ProjectNote = IDL.Record({
    'id' : IDL.Text,
    'userId' : IDL.Principal,
    'projectId' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const Package = IDL.Record({
    'id' : IDL.Text,
    'features' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'priceINR' : IDL.Nat,
  });
  const RoomType = IDL.Variant({
    'bedroom' : IDL.Null,
    'other' : IDL.Text,
    'kidsRoom' : IDL.Null,
    'office' : IDL.Null,
    'livingRoom' : IDL.Null,
    'diningRoom' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'stylePreference' : StylePreference,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'priceINR' : IDL.Nat,
    'roomType' : RoomType,
  });
  const ProductCategory = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'products' : IDL.Vec(Product),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BudgetRange = IDL.Record({
    'max' : IDL.Nat,
    'min' : IDL.Nat,
    'currency' : IDL.Text,
  });
  const ProjectBrief = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'userId' : IDL.Principal,
    'submissionDate' : Time,
    'selectedPackage' : IDL.Opt(IDL.Text),
    'stylePreferences' : IDL.Vec(StylePreference),
    'budget' : BudgetRange,
    'roomType' : RoomType,
    'timeline' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'address' : IDL.Opt(IDL.Text),
    'stylePreferences' : IDL.Vec(StylePreference),
    'phone' : IDL.Text,
  });
  const ConsultationRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'userId' : IDL.Principal,
    'projectId' : IDL.Opt(IDL.Text),
    'notes' : IDL.Text,
    'submissionDate' : Time,
    'requestedTime' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDesigner' : IDL.Func([Designer], [], []),
    'addNote' : IDL.Func([ProjectNote], [], []),
    'addPackage' : IDL.Func([Package], [], []),
    'addProductCategory' : IDL.Func([ProductCategory], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProjectBrief' : IDL.Func([ProjectBrief], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConsultationsForProject' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ConsultationRequest)],
        ['query'],
      ),
    'getDesigners' : IDL.Func([], [IDL.Vec(Designer)], ['query']),
    'getNotesForProject' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProjectNote)],
        ['query'],
      ),
    'getPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
    'getProductCategories' : IDL.Func(
        [],
        [IDL.Vec(ProductCategory)],
        ['query'],
      ),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProjectBrief' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ProjectBrief)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProjectBriefs' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ProjectBrief)],
        ['query'],
      ),
    'initializeProductCategories' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'requestConsultation' : IDL.Func([ConsultationRequest], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };