/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BudgetRange {
  'max' : bigint,
  'min' : bigint,
  'currency' : string,
}
export interface BuyerInfo {
  'name' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface ConsultationRequest {
  'id' : string,
  'status' : string,
  'userId' : Principal,
  'projectId' : [] | [string],
  'notes' : string,
  'submissionDate' : Time,
  'requestedTime' : Time,
}
export interface DeliveryAddress {
  'country' : string,
  'city' : string,
  'postalCode' : string,
  'fullName' : string,
  'state' : string,
  'addressLine1' : string,
  'addressLine2' : [] | [string],
  'phoneNumber' : string,
}
export interface Designer {
  'id' : string,
  'bio' : string,
  'portfolio' : Array<PortfolioItem>,
  'styles' : Array<StylePreference>,
  'name' : string,
}
export interface FurnitureCategory {
  'id' : string,
  'subCategory' : FurnitureSubCategory,
  'name' : string,
  'description' : string,
  'products' : Array<Product>,
}
export type FurnitureSubCategory = { 'bedSideTables' : null } |
  { 'sofa' : null } |
  { 'sofaChairs' : null } |
  { 'cornerTable' : null } |
  { 'studyTable' : null } |
  { 'kingSizeBed' : null } |
  { 'recliners' : null } |
  { 'crockeryUnit' : null } |
  { 'queenSizeBed' : null } |
  { 'dressingTable' : null } |
  { 'centerTable' : null } |
  { 'diningTable' : null };
export interface Order {
  'id' : string,
  'status' : string,
  'deliveryAddress' : DeliveryAddress,
  'paymentMethod' : PaymentMethod,
  'createdAt' : Time,
  'totalAmount' : bigint,
  'buyerId' : Principal,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'productId' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export interface OtpRequest { 'mobileNumber' : string }
export interface OtpVerification { 'otp' : string, 'mobileNumber' : string }
export interface Package {
  'id' : string,
  'features' : Array<string>,
  'name' : string,
  'description' : string,
  'priceINR' : bigint,
}
export type PaymentMethod = { 'upi' : null } |
  { 'wallet' : null } |
  { 'netBanking' : null };
export interface PortfolioItem {
  'id' : string,
  'description' : string,
  'style' : StylePreference,
  'imageUrl' : string,
}
export interface Product {
  'id' : string,
  'stylePreference' : StylePreference,
  'inventory' : bigint,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'brandId' : string,
  'priceINR' : bigint,
  'roomType' : RoomType,
}
export interface ProductBrand {
  'id' : string,
  'name' : string,
  'description' : string,
  'logoUrl' : string,
}
export interface ProductCategory {
  'id' : string,
  'name' : string,
  'description' : string,
  'products' : Array<Product>,
}
export interface ProjectBrief {
  'id' : string,
  'status' : string,
  'userId' : Principal,
  'submissionDate' : Time,
  'selectedPackage' : [] | [string],
  'stylePreferences' : Array<StylePreference>,
  'budget' : BudgetRange,
  'roomType' : RoomType,
  'timeline' : string,
}
export interface ProjectNote {
  'id' : string,
  'userId' : Principal,
  'projectId' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface RoomPackage {
  'id' : string,
  'productIds' : Array<string>,
  'name' : string,
  'description' : string,
  'style' : StylePreference,
  'priceINR' : bigint,
  'roomType' : RoomType,
}
export type RoomType = { 'bedroom' : null } |
  { 'other' : string } |
  { 'kidsRoom' : null } |
  { 'office' : null } |
  { 'livingRoom' : null } |
  { 'diningRoom' : null };
export type StylePreference = { 'other' : string } |
  { 'rustic' : null } |
  { 'boho' : null } |
  { 'traditional' : null } |
  { 'minimalist' : null } |
  { 'modern' : null } |
  { 'contemporary' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'address' : [] | [string],
  'stylePreferences' : Array<StylePreference>,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vendor {
  'id' : string,
  'verified' : boolean,
  'gstNumber' : string,
  'name' : string,
  'createdAt' : Time,
  'mobileNumber' : string,
}
export interface VendorInput {
  'id' : string,
  'gstNumber' : string,
  'name' : string,
  'mobileNumber' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDesigner' : ActorMethod<[Designer], undefined>,
  'addNote' : ActorMethod<[ProjectNote], undefined>,
  'addPackage' : ActorMethod<[Package], undefined>,
  'addRoomPackage' : ActorMethod<[RoomPackage], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateOrderTotal' : ActorMethod<[Array<OrderItem>], bigint>,
  'createProjectBrief' : ActorMethod<[ProjectBrief], undefined>,
  'deleteVendor' : ActorMethod<[string], undefined>,
  'findProductHelper' : ActorMethod<[string], [] | [Product]>,
  'getAllVendors' : ActorMethod<[], Array<Vendor>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConsultationsForProject' : ActorMethod<
    [string],
    Array<ConsultationRequest>
  >,
  'getDesigners' : ActorMethod<[], Array<Designer>>,
  'getFurnitureCategories' : ActorMethod<[], Array<FurnitureCategory>>,
  'getNotesForProject' : ActorMethod<[string], Array<ProjectNote>>,
  'getOrder' : ActorMethod<[string], [] | [Order]>,
  'getPackages' : ActorMethod<[], Array<Package>>,
  'getPackagesByPriceRange' : ActorMethod<[bigint, bigint], Array<RoomPackage>>,
  'getProductBrands' : ActorMethod<[], Array<ProductBrand>>,
  'getProductCategories' : ActorMethod<[], Array<ProductCategory>>,
  'getProductsByBrand' : ActorMethod<[string], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getProductsByFurnitureCategory' : ActorMethod<[string], Array<Product>>,
  'getProductsByFurnitureSubCategory' : ActorMethod<
    [FurnitureSubCategory],
    Array<Product>
  >,
  'getProductsForRoomPackage' : ActorMethod<[string], Array<Product>>,
  'getProjectBrief' : ActorMethod<[string], [] | [ProjectBrief]>,
  'getRoomPackageById' : ActorMethod<[string], [] | [RoomPackage]>,
  'getRoomPackages' : ActorMethod<[], Array<RoomPackage>>,
  'getRoomPackagesByRoomType' : ActorMethod<[RoomType], Array<RoomPackage>>,
  'getRoomPackagesByStyle' : ActorMethod<[StylePreference], Array<RoomPackage>>,
  'getRoomPackagesByStyleAndRoomType' : ActorMethod<
    [StylePreference, RoomType],
    Array<RoomPackage>
  >,
  'getStyleOptionsForRoomType' : ActorMethod<
    [RoomType],
    Array<StylePreference>
  >,
  'getUserOrders' : ActorMethod<[Principal], Array<Order>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProjectBriefs' : ActorMethod<[Principal], Array<ProjectBrief>>,
  'getVendor' : ActorMethod<[string], Vendor>,
  'getVendorByMobileNumber' : ActorMethod<[string], Vendor>,
  'getVendorsByGstNumber' : ActorMethod<[string], Array<Vendor>>,
  'globalProductSearch' : ActorMethod<[string], Array<Product>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[Order, BuyerInfo, bigint], undefined>,
  'registerVendor' : ActorMethod<[VendorInput], undefined>,
  'requestConsultation' : ActorMethod<[ConsultationRequest], undefined>,
  'requestOtp' : ActorMethod<[OtpRequest], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchFurnitureProducts' : ActorMethod<[string], Array<Product>>,
  'verifyOtp' : ActorMethod<[OtpVerification], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];