/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ProjectBrief {
    id: string;
    status: string;
    userId: Principal;
    submissionDate: Time;
    selectedPackage?: string;
    stylePreferences: Array<StylePreference>;
    budget: BudgetRange;
    roomType: RoomType;
    timeline: string;
}
export type Time = bigint;
export interface Designer {
    id: string;
    bio: string;
    portfolio: Array<PortfolioItem>;
    styles: Array<StylePreference>;
    name: string;
}
export interface OrderItem {
    productId: string;
    quantity: bigint;
    price: bigint;
}
export interface ConsultationRequest {
    id: string;
    status: string;
    userId: Principal;
    projectId?: string;
    notes: string;
    submissionDate: Time;
    requestedTime: Time;
}
export interface ProductBrand {
    id: string;
    name: string;
    description: string;
    logoUrl: string;
}
export interface Package {
    id: string;
    features: Array<string>;
    name: string;
    description: string;
    priceINR: bigint;
}
export type RoomType = {
    __kind__: "bedroom";
    bedroom: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "kidsRoom";
    kidsRoom: null;
} | {
    __kind__: "office";
    office: null;
} | {
    __kind__: "livingRoom";
    livingRoom: null;
} | {
    __kind__: "diningRoom";
    diningRoom: null;
};
export interface ProjectNote {
    id: string;
    userId: Principal;
    projectId: string;
    message: string;
    timestamp: Time;
}
export interface Order {
    id: string;
    status: string;
    deliveryAddress: DeliveryAddress;
    paymentMethod: PaymentMethod;
    createdAt: Time;
    totalAmount: bigint;
    buyerId: Principal;
    items: Array<OrderItem>;
}
export interface RoomPackage {
    id: string;
    productIds: Array<string>;
    name: string;
    description: string;
    style: StylePreference;
    priceINR: bigint;
    roomType: RoomType;
}
export interface BudgetRange {
    max: bigint;
    min: bigint;
    currency: string;
}
export type StylePreference = {
    __kind__: "other";
    other: string;
} | {
    __kind__: "rustic";
    rustic: null;
} | {
    __kind__: "boho";
    boho: null;
} | {
    __kind__: "traditional";
    traditional: null;
} | {
    __kind__: "minimalist";
    minimalist: null;
} | {
    __kind__: "modern";
    modern: null;
} | {
    __kind__: "contemporary";
    contemporary: null;
};
export interface PortfolioItem {
    id: string;
    description: string;
    style: StylePreference;
    imageUrl: string;
}
export interface DeliveryAddress {
    country: string;
    city: string;
    postalCode: string;
    fullName: string;
    state: string;
    addressLine1: string;
    addressLine2?: string;
    phoneNumber: string;
}
export interface ProductCategory {
    id: string;
    name: string;
    description: string;
    products: Array<Product>;
}
export interface UserProfile {
    name: string;
    createdAt: Time;
    email: string;
    address?: string;
    stylePreferences: Array<StylePreference>;
    phone: string;
}
export interface Product {
    id: string;
    stylePreference: StylePreference;
    inventory: bigint;
    name: string;
    description: string;
    imageUrl: string;
    brandId: string;
    priceINR: bigint;
    roomType: RoomType;
}
export enum PaymentMethod {
    upi = "upi",
    wallet = "wallet",
    netBanking = "netBanking"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addDesigner(designer: Designer): Promise<void>;
    addNote(note: ProjectNote): Promise<void>;
    addPackage(pkg: Package): Promise<void>;
    addRoomPackage(pkg: RoomPackage): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createProjectBrief(brief: ProjectBrief): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getConsultationsForProject(projectId: string): Promise<Array<ConsultationRequest>>;
    getDesigners(): Promise<Array<Designer>>;
    getNotesForProject(projectId: string): Promise<Array<ProjectNote>>;
    getOrder(orderId: string): Promise<Order | null>;
    getPackages(): Promise<Array<Package>>;
    getProductBrands(): Promise<Array<ProductBrand>>;
    getProductCategories(): Promise<Array<ProductCategory>>;
    getProductsByBrand(brandId: string): Promise<Array<Product>>;
    getProductsByCategory(categoryId: string): Promise<Array<Product>>;
    getProductsForRoomPackage(packageId: string): Promise<Array<Product>>;
    getProjectBrief(id: string): Promise<ProjectBrief | null>;
    getRoomPackageById(packageId: string): Promise<RoomPackage | null>;
    getRoomPackages(): Promise<Array<RoomPackage>>;
    getRoomPackagesByRoomType(roomType: RoomType): Promise<Array<RoomPackage>>;
    getRoomPackagesByStyle(style: StylePreference): Promise<Array<RoomPackage>>;
    getRoomPackagesByStyleAndRoomType(style: StylePreference, roomType: RoomType): Promise<Array<RoomPackage>>;
    getStyleOptionsForRoomType(roomType: RoomType): Promise<Array<StylePreference>>;
    getUserOrders(userId: Principal): Promise<Array<Order>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserProjectBriefs(userId: Principal): Promise<Array<ProjectBrief>>;
    isCallerAdmin(): Promise<boolean>;
    placeOrder(order: Order): Promise<void>;
    requestConsultation(request: ConsultationRequest): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { BudgetRange as _BudgetRange, ConsultationRequest as _ConsultationRequest, DeliveryAddress as _DeliveryAddress, Designer as _Designer, Order as _Order, OrderItem as _OrderItem, PaymentMethod as _PaymentMethod, PortfolioItem as _PortfolioItem, Product as _Product, ProductCategory as _ProductCategory, ProjectBrief as _ProjectBrief, RoomPackage as _RoomPackage, RoomType as _RoomType, StylePreference as _StylePreference, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addDesigner(arg0: Designer): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDesigner(to_candid_Designer_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDesigner(to_candid_Designer_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addNote(arg0: ProjectNote): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNote(arg0);
            return result;
        }
    }
    async addPackage(arg0: Package): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPackage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPackage(arg0);
            return result;
        }
    }
    async addRoomPackage(arg0: RoomPackage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRoomPackage(to_candid_RoomPackage_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRoomPackage(to_candid_RoomPackage_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createProjectBrief(arg0: ProjectBrief): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createProjectBrief(to_candid_ProjectBrief_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProjectBrief(to_candid_ProjectBrief_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConsultationsForProject(arg0: string): Promise<Array<ConsultationRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConsultationsForProject(arg0);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConsultationsForProject(arg0);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDesigners(): Promise<Array<Designer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDesigners();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDesigners();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotesForProject(arg0: string): Promise<Array<ProjectNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotesForProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotesForProject(arg0);
            return result;
        }
    }
    async getOrder(arg0: string): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPackages(): Promise<Array<Package>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPackages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPackages();
            return result;
        }
    }
    async getProductBrands(): Promise<Array<ProductBrand>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductBrands();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductBrands();
            return result;
        }
    }
    async getProductCategories(): Promise<Array<ProductCategory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductCategories();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductCategories();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductsByBrand(arg0: string): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByBrand(arg0);
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByBrand(arg0);
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductsByCategory(arg0: string): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByCategory(arg0);
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByCategory(arg0);
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductsForRoomPackage(arg0: string): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsForRoomPackage(arg0);
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsForRoomPackage(arg0);
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjectBrief(arg0: string): Promise<ProjectBrief | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectBrief(arg0);
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectBrief(arg0);
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoomPackageById(arg0: string): Promise<RoomPackage | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomPackageById(arg0);
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomPackageById(arg0);
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoomPackages(): Promise<Array<RoomPackage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomPackages();
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomPackages();
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoomPackagesByRoomType(arg0: RoomType): Promise<Array<RoomPackage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomPackagesByRoomType(to_candid_RoomType_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomPackagesByRoomType(to_candid_RoomType_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoomPackagesByStyle(arg0: StylePreference): Promise<Array<RoomPackage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomPackagesByStyle(to_candid_StylePreference_n6(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomPackagesByStyle(to_candid_StylePreference_n6(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoomPackagesByStyleAndRoomType(arg0: StylePreference, arg1: RoomType): Promise<Array<RoomPackage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomPackagesByStyleAndRoomType(to_candid_StylePreference_n6(this._uploadFile, this._downloadFile, arg0), to_candid_RoomType_n11(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomPackagesByStyleAndRoomType(to_candid_StylePreference_n6(this._uploadFile, this._downloadFile, arg0), to_candid_RoomType_n11(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStyleOptionsForRoomType(arg0: RoomType): Promise<Array<StylePreference>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStyleOptionsForRoomType(to_candid_RoomType_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStyleOptionsForRoomType(to_candid_RoomType_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserOrders(arg0: Principal): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserOrders(arg0);
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserOrders(arg0);
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProjectBriefs(arg0: Principal): Promise<Array<ProjectBrief>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProjectBriefs(arg0);
                return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProjectBriefs(arg0);
            return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async placeOrder(arg0: Order): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(to_candid_Order_n59(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(to_candid_Order_n59(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async requestConsultation(arg0: ConsultationRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestConsultation(to_candid_ConsultationRequest_n65(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestConsultation(to_candid_ConsultationRequest_n65(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n67(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n67(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_ConsultationRequest_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConsultationRequest): ConsultationRequest {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_DeliveryAddress_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeliveryAddress): DeliveryAddress {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Designer_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Designer): Designer {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_PortfolioItem_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PortfolioItem): PortfolioItem {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_ProductCategory_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductCategory): ProductCategory {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectBrief_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectBrief): ProjectBrief {
    return from_candid_record_n52(_uploadFile, _downloadFile, value);
}
function from_candid_RoomPackage_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoomPackage): RoomPackage {
    return from_candid_record_n55(_uploadFile, _downloadFile, value);
}
function from_candid_RoomType_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoomType): RoomType {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_StylePreference_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StylePreference): StylePreference {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n36(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProjectBrief]): ProjectBrief | null {
    return value.length === 0 ? null : from_candid_ProjectBrief_n51(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RoomPackage]): RoomPackage | null {
    return value.length === 0 ? null : from_candid_RoomPackage_n54(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    createdAt: _Time;
    email: string;
    address: [] | [string];
    stylePreferences: Array<_StylePreference>;
    phone: string;
}): {
    name: string;
    createdAt: Time;
    email: string;
    address?: string;
    stylePreferences: Array<StylePreference>;
    phone: string;
} {
    return {
        name: value.name,
        createdAt: value.createdAt,
        email: value.email,
        address: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.address)),
        stylePreferences: from_candid_vec_n21(_uploadFile, _downloadFile, value.stylePreferences),
        phone: value.phone
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    userId: Principal;
    projectId: [] | [string];
    notes: string;
    submissionDate: _Time;
    requestedTime: _Time;
}): {
    id: string;
    status: string;
    userId: Principal;
    projectId?: string;
    notes: string;
    submissionDate: Time;
    requestedTime: Time;
} {
    return {
        id: value.id,
        status: value.status,
        userId: value.userId,
        projectId: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.projectId)),
        notes: value.notes,
        submissionDate: value.submissionDate,
        requestedTime: value.requestedTime
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    bio: string;
    portfolio: Array<_PortfolioItem>;
    styles: Array<_StylePreference>;
    name: string;
}): {
    id: string;
    bio: string;
    portfolio: Array<PortfolioItem>;
    styles: Array<StylePreference>;
    name: string;
} {
    return {
        id: value.id,
        bio: value.bio,
        portfolio: from_candid_vec_n32(_uploadFile, _downloadFile, value.portfolio),
        styles: from_candid_vec_n21(_uploadFile, _downloadFile, value.styles),
        name: value.name
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    description: string;
    style: _StylePreference;
    imageUrl: string;
}): {
    id: string;
    description: string;
    style: StylePreference;
    imageUrl: string;
} {
    return {
        id: value.id,
        description: value.description,
        style: from_candid_StylePreference_n22(_uploadFile, _downloadFile, value.style),
        imageUrl: value.imageUrl
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    deliveryAddress: _DeliveryAddress;
    paymentMethod: _PaymentMethod;
    createdAt: _Time;
    totalAmount: bigint;
    buyerId: Principal;
    items: Array<_OrderItem>;
}): {
    id: string;
    status: string;
    deliveryAddress: DeliveryAddress;
    paymentMethod: PaymentMethod;
    createdAt: Time;
    totalAmount: bigint;
    buyerId: Principal;
    items: Array<OrderItem>;
} {
    return {
        id: value.id,
        status: value.status,
        deliveryAddress: from_candid_DeliveryAddress_n38(_uploadFile, _downloadFile, value.deliveryAddress),
        paymentMethod: from_candid_PaymentMethod_n40(_uploadFile, _downloadFile, value.paymentMethod),
        createdAt: value.createdAt,
        totalAmount: value.totalAmount,
        buyerId: value.buyerId,
        items: value.items
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    country: string;
    city: string;
    postalCode: string;
    fullName: string;
    state: string;
    addressLine1: string;
    addressLine2: [] | [string];
    phoneNumber: string;
}): {
    country: string;
    city: string;
    postalCode: string;
    fullName: string;
    state: string;
    addressLine1: string;
    addressLine2?: string;
    phoneNumber: string;
} {
    return {
        country: value.country,
        city: value.city,
        postalCode: value.postalCode,
        fullName: value.fullName,
        state: value.state,
        addressLine1: value.addressLine1,
        addressLine2: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.addressLine2)),
        phoneNumber: value.phoneNumber
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    description: string;
    products: Array<_Product>;
}): {
    id: string;
    name: string;
    description: string;
    products: Array<Product>;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        products: from_candid_vec_n45(_uploadFile, _downloadFile, value.products)
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    stylePreference: _StylePreference;
    inventory: bigint;
    name: string;
    description: string;
    imageUrl: string;
    brandId: string;
    priceINR: bigint;
    roomType: _RoomType;
}): {
    id: string;
    stylePreference: StylePreference;
    inventory: bigint;
    name: string;
    description: string;
    imageUrl: string;
    brandId: string;
    priceINR: bigint;
    roomType: RoomType;
} {
    return {
        id: value.id,
        stylePreference: from_candid_StylePreference_n22(_uploadFile, _downloadFile, value.stylePreference),
        inventory: value.inventory,
        name: value.name,
        description: value.description,
        imageUrl: value.imageUrl,
        brandId: value.brandId,
        priceINR: value.priceINR,
        roomType: from_candid_RoomType_n48(_uploadFile, _downloadFile, value.roomType)
    };
}
function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    userId: Principal;
    submissionDate: _Time;
    selectedPackage: [] | [string];
    stylePreferences: Array<_StylePreference>;
    budget: _BudgetRange;
    roomType: _RoomType;
    timeline: string;
}): {
    id: string;
    status: string;
    userId: Principal;
    submissionDate: Time;
    selectedPackage?: string;
    stylePreferences: Array<StylePreference>;
    budget: BudgetRange;
    roomType: RoomType;
    timeline: string;
} {
    return {
        id: value.id,
        status: value.status,
        userId: value.userId,
        submissionDate: value.submissionDate,
        selectedPackage: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.selectedPackage)),
        stylePreferences: from_candid_vec_n21(_uploadFile, _downloadFile, value.stylePreferences),
        budget: value.budget,
        roomType: from_candid_RoomType_n48(_uploadFile, _downloadFile, value.roomType),
        timeline: value.timeline
    };
}
function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    productIds: Array<string>;
    name: string;
    description: string;
    style: _StylePreference;
    priceINR: bigint;
    roomType: _RoomType;
}): {
    id: string;
    productIds: Array<string>;
    name: string;
    description: string;
    style: StylePreference;
    priceINR: bigint;
    roomType: RoomType;
} {
    return {
        id: value.id,
        productIds: value.productIds,
        name: value.name,
        description: value.description,
        style: from_candid_StylePreference_n22(_uploadFile, _downloadFile, value.style),
        priceINR: value.priceINR,
        roomType: from_candid_RoomType_n48(_uploadFile, _downloadFile, value.roomType)
    };
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: string;
} | {
    rustic: null;
} | {
    boho: null;
} | {
    traditional: null;
} | {
    minimalist: null;
} | {
    modern: null;
} | {
    contemporary: null;
}): {
    __kind__: "other";
    other: string;
} | {
    __kind__: "rustic";
    rustic: null;
} | {
    __kind__: "boho";
    boho: null;
} | {
    __kind__: "traditional";
    traditional: null;
} | {
    __kind__: "minimalist";
    minimalist: null;
} | {
    __kind__: "modern";
    modern: null;
} | {
    __kind__: "contemporary";
    contemporary: null;
} {
    return "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "rustic" in value ? {
        __kind__: "rustic",
        rustic: value.rustic
    } : "boho" in value ? {
        __kind__: "boho",
        boho: value.boho
    } : "traditional" in value ? {
        __kind__: "traditional",
        traditional: value.traditional
    } : "minimalist" in value ? {
        __kind__: "minimalist",
        minimalist: value.minimalist
    } : "modern" in value ? {
        __kind__: "modern",
        modern: value.modern
    } : "contemporary" in value ? {
        __kind__: "contemporary",
        contemporary: value.contemporary
    } : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upi: null;
} | {
    wallet: null;
} | {
    netBanking: null;
}): PaymentMethod {
    return "upi" in value ? PaymentMethod.upi : "wallet" in value ? PaymentMethod.wallet : "netBanking" in value ? PaymentMethod.netBanking : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bedroom: null;
} | {
    other: string;
} | {
    kidsRoom: null;
} | {
    office: null;
} | {
    livingRoom: null;
} | {
    diningRoom: null;
}): {
    __kind__: "bedroom";
    bedroom: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "kidsRoom";
    kidsRoom: null;
} | {
    __kind__: "office";
    office: null;
} | {
    __kind__: "livingRoom";
    livingRoom: null;
} | {
    __kind__: "diningRoom";
    diningRoom: null;
} {
    return "bedroom" in value ? {
        __kind__: "bedroom",
        bedroom: value.bedroom
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "kidsRoom" in value ? {
        __kind__: "kidsRoom",
        kidsRoom: value.kidsRoom
    } : "office" in value ? {
        __kind__: "office",
        office: value.office
    } : "livingRoom" in value ? {
        __kind__: "livingRoom",
        livingRoom: value.livingRoom
    } : "diningRoom" in value ? {
        __kind__: "diningRoom",
        diningRoom: value.diningRoom
    } : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StylePreference>): Array<StylePreference> {
    return value.map((x)=>from_candid_StylePreference_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ConsultationRequest>): Array<ConsultationRequest> {
    return value.map((x)=>from_candid_ConsultationRequest_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Designer>): Array<Designer> {
    return value.map((x)=>from_candid_Designer_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PortfolioItem>): Array<PortfolioItem> {
    return value.map((x)=>from_candid_PortfolioItem_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProductCategory>): Array<ProductCategory> {
    return value.map((x)=>from_candid_ProductCategory_n43(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n46(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RoomPackage>): Array<RoomPackage> {
    return value.map((x)=>from_candid_RoomPackage_n54(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProjectBrief>): Array<ProjectBrief> {
    return value.map((x)=>from_candid_ProjectBrief_n51(_uploadFile, _downloadFile, x));
}
function to_candid_ConsultationRequest_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ConsultationRequest): _ConsultationRequest {
    return to_candid_record_n66(_uploadFile, _downloadFile, value);
}
function to_candid_DeliveryAddress_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeliveryAddress): _DeliveryAddress {
    return to_candid_record_n62(_uploadFile, _downloadFile, value);
}
function to_candid_Designer_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Designer): _Designer {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Order_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Order): _Order {
    return to_candid_record_n60(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n64(_uploadFile, _downloadFile, value);
}
function to_candid_PortfolioItem_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PortfolioItem): _PortfolioItem {
    return to_candid_record_n5(_uploadFile, _downloadFile, value);
}
function to_candid_ProjectBrief_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectBrief): _ProjectBrief {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_RoomPackage_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoomPackage): _RoomPackage {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_RoomType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoomType): _RoomType {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_StylePreference_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StylePreference): _StylePreference {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n68(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    productIds: Array<string>;
    name: string;
    description: string;
    style: StylePreference;
    priceINR: bigint;
    roomType: RoomType;
}): {
    id: string;
    productIds: Array<string>;
    name: string;
    description: string;
    style: _StylePreference;
    priceINR: bigint;
    roomType: _RoomType;
} {
    return {
        id: value.id,
        productIds: value.productIds,
        name: value.name,
        description: value.description,
        style: to_candid_StylePreference_n6(_uploadFile, _downloadFile, value.style),
        priceINR: value.priceINR,
        roomType: to_candid_RoomType_n11(_uploadFile, _downloadFile, value.roomType)
    };
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    userId: Principal;
    submissionDate: Time;
    selectedPackage?: string;
    stylePreferences: Array<StylePreference>;
    budget: BudgetRange;
    roomType: RoomType;
    timeline: string;
}): {
    id: string;
    status: string;
    userId: Principal;
    submissionDate: _Time;
    selectedPackage: [] | [string];
    stylePreferences: Array<_StylePreference>;
    budget: _BudgetRange;
    roomType: _RoomType;
    timeline: string;
} {
    return {
        id: value.id,
        status: value.status,
        userId: value.userId,
        submissionDate: value.submissionDate,
        selectedPackage: value.selectedPackage ? candid_some(value.selectedPackage) : candid_none(),
        stylePreferences: to_candid_vec_n8(_uploadFile, _downloadFile, value.stylePreferences),
        budget: value.budget,
        roomType: to_candid_RoomType_n11(_uploadFile, _downloadFile, value.roomType),
        timeline: value.timeline
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    bio: string;
    portfolio: Array<PortfolioItem>;
    styles: Array<StylePreference>;
    name: string;
}): {
    id: string;
    bio: string;
    portfolio: Array<_PortfolioItem>;
    styles: Array<_StylePreference>;
    name: string;
} {
    return {
        id: value.id,
        bio: value.bio,
        portfolio: to_candid_vec_n3(_uploadFile, _downloadFile, value.portfolio),
        styles: to_candid_vec_n8(_uploadFile, _downloadFile, value.styles),
        name: value.name
    };
}
function to_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    description: string;
    style: StylePreference;
    imageUrl: string;
}): {
    id: string;
    description: string;
    style: _StylePreference;
    imageUrl: string;
} {
    return {
        id: value.id,
        description: value.description,
        style: to_candid_StylePreference_n6(_uploadFile, _downloadFile, value.style),
        imageUrl: value.imageUrl
    };
}
function to_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    deliveryAddress: DeliveryAddress;
    paymentMethod: PaymentMethod;
    createdAt: Time;
    totalAmount: bigint;
    buyerId: Principal;
    items: Array<OrderItem>;
}): {
    id: string;
    status: string;
    deliveryAddress: _DeliveryAddress;
    paymentMethod: _PaymentMethod;
    createdAt: _Time;
    totalAmount: bigint;
    buyerId: Principal;
    items: Array<_OrderItem>;
} {
    return {
        id: value.id,
        status: value.status,
        deliveryAddress: to_candid_DeliveryAddress_n61(_uploadFile, _downloadFile, value.deliveryAddress),
        paymentMethod: to_candid_PaymentMethod_n63(_uploadFile, _downloadFile, value.paymentMethod),
        createdAt: value.createdAt,
        totalAmount: value.totalAmount,
        buyerId: value.buyerId,
        items: value.items
    };
}
function to_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    country: string;
    city: string;
    postalCode: string;
    fullName: string;
    state: string;
    addressLine1: string;
    addressLine2?: string;
    phoneNumber: string;
}): {
    country: string;
    city: string;
    postalCode: string;
    fullName: string;
    state: string;
    addressLine1: string;
    addressLine2: [] | [string];
    phoneNumber: string;
} {
    return {
        country: value.country,
        city: value.city,
        postalCode: value.postalCode,
        fullName: value.fullName,
        state: value.state,
        addressLine1: value.addressLine1,
        addressLine2: value.addressLine2 ? candid_some(value.addressLine2) : candid_none(),
        phoneNumber: value.phoneNumber
    };
}
function to_candid_record_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    userId: Principal;
    projectId?: string;
    notes: string;
    submissionDate: Time;
    requestedTime: Time;
}): {
    id: string;
    status: string;
    userId: Principal;
    projectId: [] | [string];
    notes: string;
    submissionDate: _Time;
    requestedTime: _Time;
} {
    return {
        id: value.id,
        status: value.status,
        userId: value.userId,
        projectId: value.projectId ? candid_some(value.projectId) : candid_none(),
        notes: value.notes,
        submissionDate: value.submissionDate,
        requestedTime: value.requestedTime
    };
}
function to_candid_record_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    createdAt: Time;
    email: string;
    address?: string;
    stylePreferences: Array<StylePreference>;
    phone: string;
}): {
    name: string;
    createdAt: _Time;
    email: string;
    address: [] | [string];
    stylePreferences: Array<_StylePreference>;
    phone: string;
} {
    return {
        name: value.name,
        createdAt: value.createdAt,
        email: value.email,
        address: value.address ? candid_some(value.address) : candid_none(),
        stylePreferences: to_candid_vec_n8(_uploadFile, _downloadFile, value.stylePreferences),
        phone: value.phone
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "bedroom";
    bedroom: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "kidsRoom";
    kidsRoom: null;
} | {
    __kind__: "office";
    office: null;
} | {
    __kind__: "livingRoom";
    livingRoom: null;
} | {
    __kind__: "diningRoom";
    diningRoom: null;
}): {
    bedroom: null;
} | {
    other: string;
} | {
    kidsRoom: null;
} | {
    office: null;
} | {
    livingRoom: null;
} | {
    diningRoom: null;
} {
    return value.__kind__ === "bedroom" ? {
        bedroom: value.bedroom
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "kidsRoom" ? {
        kidsRoom: value.kidsRoom
    } : value.__kind__ === "office" ? {
        office: value.office
    } : value.__kind__ === "livingRoom" ? {
        livingRoom: value.livingRoom
    } : value.__kind__ === "diningRoom" ? {
        diningRoom: value.diningRoom
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    upi: null;
} | {
    wallet: null;
} | {
    netBanking: null;
} {
    return value == PaymentMethod.upi ? {
        upi: null
    } : value == PaymentMethod.wallet ? {
        wallet: null
    } : value == PaymentMethod.netBanking ? {
        netBanking: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "other";
    other: string;
} | {
    __kind__: "rustic";
    rustic: null;
} | {
    __kind__: "boho";
    boho: null;
} | {
    __kind__: "traditional";
    traditional: null;
} | {
    __kind__: "minimalist";
    minimalist: null;
} | {
    __kind__: "modern";
    modern: null;
} | {
    __kind__: "contemporary";
    contemporary: null;
}): {
    other: string;
} | {
    rustic: null;
} | {
    boho: null;
} | {
    traditional: null;
} | {
    minimalist: null;
} | {
    modern: null;
} | {
    contemporary: null;
} {
    return value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "rustic" ? {
        rustic: value.rustic
    } : value.__kind__ === "boho" ? {
        boho: value.boho
    } : value.__kind__ === "traditional" ? {
        traditional: value.traditional
    } : value.__kind__ === "minimalist" ? {
        minimalist: value.minimalist
    } : value.__kind__ === "modern" ? {
        modern: value.modern
    } : value.__kind__ === "contemporary" ? {
        contemporary: value.contemporary
    } : value;
}
function to_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<PortfolioItem>): Array<_PortfolioItem> {
    return value.map((x)=>to_candid_PortfolioItem_n4(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<StylePreference>): Array<_StylePreference> {
    return value.map((x)=>to_candid_StylePreference_n6(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
